name: Build MacOS
run-name: Build MacOS

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  Build_MacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            flutter/.pub-cache
          key: ${{ runner.os }}-arm64-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-arm64-pub-cache

      - run: sudo xcode-select --switch /Applications/Xcode_14.3.1.app
      - run: flutter pub get
      - run: flutter build macos --release
      - run: |
          cd build/macos/Build/Products/Release/
          mv pica_comic.app PicaComic.app
          zip -r PicaComic-macos-universal.zip PicaComic.app
          mkdir build_dmg
          mv PicaComic.app build_dmg/
          ln -s /Applications build_dmg/Applications
          hdiutil create -volname "PicaComic" -srcfolder build_dmg -ov -format UDZO PicaComic-macos-universal.dmg
          mkdir build_files
          mv PicaComic-macos-universal.* build_files/
      - uses: actions/upload-artifact@v4
        with:
          name: PicaComic-macos-universal
          path: build/macos/Build/Products/Release/build_files
