name: Build Windows
run-name: Build Windows

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  Build_Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            flutter/.pub-cache
          key: ${{ runner.os }}-amd64-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-amd64-pub-cache

      - run: |
          curl -O ChineseSimplified.isl https://raw.githubusercontent.com/jrsoftware/issrc/refs/heads/main/Files/Languages/Unofficial/ChineseSimplified.isl
          mv ChineseSimplified.isl "C:\Program Files (x86)\Inno Setup 6\Languages"
          python3 windows/build_windows.py

      - uses: actions/upload-artifact@v4
        with:
          name: PicaComic-windows-portable
          path: build/windows/x64/runner/Release
      - uses: actions/upload-artifact@v4
        with:
          name: PicaComic-windows-installer
          path: build/windows/PicaComic-windows-installer.exe
